// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoqaeG7qClU-aDakLZJSzbsAhKhjWlaZ0',
    appId: '1:196212555746:web:2726bcbf6b415a71a1c3bb',
    messagingSenderId: '196212555746',
    projectId: 'lapor-book-cb5bb',
    authDomain: 'lapor-book-cb5bb.firebaseapp.com',
    storageBucket: 'lapor-book-cb5bb.appspot.com',
    measurementId: 'G-J678LQEZHN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADowk5SftAGvKzl6eJSZS5WZrWJcLxC0M',
    appId: '1:196212555746:android:85a031c14c174fb7a1c3bb',
    messagingSenderId: '196212555746',
    projectId: 'lapor-book-cb5bb',
    storageBucket: 'lapor-book-cb5bb.appspot.com',
  );
}
